//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnipetModuleEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OmnipetModuleEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add Module.
        /// </summary>
        internal static string AddModuleTitle {
            get {
                return ResourceManager.GetString("AddModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Background &quot;{0}&quot; already exists..
        /// </summary>
        internal static string BackgroundsPanel_AlreadyExists {
            get {
                return ResourceManager.GetString("BackgroundsPanel_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select background PNG.
        /// </summary>
        internal static string BackgroundsPanel_ImportTitle {
            get {
                return ResourceManager.GetString("BackgroundsPanel_ImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fast Editor.
        /// </summary>
        internal static string BattleTab_Button_FastEditor {
            get {
                return ResourceManager.GetString("BattleTab_Button_FastEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Do you want to remove the enemy &quot;{0}&quot;?.
        /// </summary>
        internal static string BattleTab_ConfirmRemove {
            get {
                return ResourceManager.GetString("BattleTab_ConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  Copy.
        /// </summary>
        internal static string BattleTab_CopySuffix {
            get {
                return ResourceManager.GetString("BattleTab_CopySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error loading battle.json: {0}.
        /// </summary>
        internal static string BattleTab_ErrorLoading {
            get {
                return ResourceManager.GetString("BattleTab_ErrorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error loading monster.json: {0}.
        /// </summary>
        internal static string BattleTab_ErrorLoadingMonster {
            get {
                return ResourceManager.GetString("BattleTab_ErrorLoadingMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error saving battle.json: {0}.
        /// </summary>
        internal static string BattleTab_ErrorSaving {
            get {
                return ResourceManager.GetString("BattleTab_ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ver. {0} | Stage {1} | Area {2} | Round {3}.
        /// </summary>
        internal static string BattleTab_Label_Info {
            get {
                return ResourceManager.GetString("BattleTab_Label_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a New Enemy.
        /// </summary>
        internal static string BattleTab_NewEnemyName {
            get {
                return ResourceManager.GetString("BattleTab_NewEnemyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add.
        /// </summary>
        internal static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Copy.
        /// </summary>
        internal static string Button_Copy {
            get {
                return ResourceManager.GetString("Button_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete.
        /// </summary>
        internal static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Download.
        /// </summary>
        internal static string Button_Download {
            get {
                return ResourceManager.GetString("Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Import.
        /// </summary>
        internal static string Button_Import {
            get {
                return ResourceManager.GetString("Button_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OK.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Organize.
        /// </summary>
        internal static string Button_Organize {
            get {
                return ResourceManager.GetString("Button_Organize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Paste.
        /// </summary>
        internal static string Button_Paste {
            get {
                return ResourceManager.GetString("Button_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Refresh.
        /// </summary>
        internal static string Button_Refresh {
            get {
                return ResourceManager.GetString("Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remove.
        /// </summary>
        internal static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Toggle Connect.
        /// </summary>
        internal static string Button_ToggleConnect {
            get {
                return ResourceManager.GetString("Button_ToggleConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Are you sure you want to delete this folder? This action cannot be undone..
        /// </summary>
        internal static string ConfirmDeleteFolder {
            get {
                return ResourceManager.GetString("ConfirmDeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirm Deletion.
        /// </summary>
        internal static string ConfirmDeletionTitle {
            get {
                return ResourceManager.GetString("ConfirmDeletionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Do you want to remove the pet &quot;{0}&quot;?.
        /// </summary>
        internal static string ConfirmRemovePet {
            get {
                return ResourceManager.GetString("ConfirmRemovePet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Could not copy the name to the clipboard..
        /// </summary>
        internal static string CouldNotCopyName {
            get {
                return ResourceManager.GetString("CouldNotCopyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Could not open the browser..
        /// </summary>
        internal static string CouldNotOpenBrowser {
            get {
                return ResourceManager.GetString("CouldNotOpenBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pet:.
        /// </summary>
        internal static string EnemyAddDialog_Label_Pet {
            get {
                return ResourceManager.GetString("EnemyAddDialog_Label_Pet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Version:.
        /// </summary>
        internal static string EnemyAddDialog_Label_Version {
            get {
                return ResourceManager.GetString("EnemyAddDialog_Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Custom.
        /// </summary>
        internal static string EnemyAddDialog_PetItem_Custom {
            get {
                return ResourceManager.GetString("EnemyAddDialog_PetItem_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add Enemy.
        /// </summary>
        internal static string EnemyAddDialog_Title {
            get {
                return ResourceManager.GetString("EnemyAddDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Version {0}.
        /// </summary>
        internal static string EnemyAddDialog_VersionItem {
            get {
                return ResourceManager.GetString("EnemyAddDialog_VersionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error listing folders: {0}.
        /// </summary>
        internal static string ErrorListingFolders {
            get {
                return ResourceManager.GetString("ErrorListingFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error loading module: {0}.
        /// </summary>
        internal static string ErrorLoadingModule {
            get {
                return ResourceManager.GetString("ErrorLoadingModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error loading monster.json: {0}.
        /// </summary>
        internal static string ErrorLoadingMonster {
            get {
                return ResourceManager.GetString("ErrorLoadingMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error removing folder: {0}.
        /// </summary>
        internal static string ErrorRemovingFolder {
            get {
                return ResourceManager.GetString("ErrorRemovingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error saving monster.json: {0}.
        /// </summary>
        internal static string ErrorSavingMonster {
            get {
                return ResourceManager.GetString("ErrorSavingMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error copying criteria: .
        /// </summary>
        internal static string EvolutionCriteriaForm_ErrorCopy {
            get {
                return ResourceManager.GetString("EvolutionCriteriaForm_ErrorCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid data in clipboard..
        /// </summary>
        internal static string EvolutionCriteriaForm_ErrorInvalidClipboard {
            get {
                return ResourceManager.GetString("EvolutionCriteriaForm_ErrorInvalidClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error pasting criteria: .
        /// </summary>
        internal static string EvolutionCriteriaForm_ErrorPaste {
            get {
                return ResourceManager.GetString("EvolutionCriteriaForm_ErrorPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Area.
        /// </summary>
        internal static string EvolutionCriteriaForm_LabelArea {
            get {
                return ResourceManager.GetString("EvolutionCriteriaForm_LabelArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Attribute (Jogress).
        /// </summary>
        internal static string EvolutionCriteriaForm_LabelAttributeJogress {
            get {
                return ResourceManager.GetString("EvolutionCriteriaForm_LabelAttributeJogress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Battles.
        /// </summary>
        internal static string EvolutionCriteriaForm_LabelBattles {
            get {
                return ResourceManager.GetString("EvolutionCriteriaForm_LabelBattles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Condition Hearts.
        /// </summary>
        internal static string EvolutionCriteriaForm_LabelConditionHearts {
            get {
                return ResourceManager.GetString("EvolutionCriteriaForm_LabelConditionHearts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Item.
        /// </summary>
        internal static string EvolutionCriteriaForm_LabelItem {
            get {
                return ResourceManager.GetString("EvolutionCriteriaForm_LabelItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jogress Name.
        /// </summary>
        internal static string EvolutionCriteriaForm_LabelJogressName {
            get {
                return ResourceManager.GetString("EvolutionCriteriaForm_LabelJogressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Level.
        /// </summary>
        internal static string EvolutionCriteriaForm_LabelLevel {
            get {
                return ResourceManager.GetString("EvolutionCriteriaForm_LabelLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mistakes.
        /// </summary>
        internal static string EvolutionCriteriaForm_LabelMistakes {
            get {
                return ResourceManager.GetString("EvolutionCriteriaForm_LabelMistakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Overfeed.
        /// </summary>
        internal static string EvolutionCriteriaForm_LabelOverfeed {
            get {
                return ResourceManager.GetString("EvolutionCriteriaForm_LabelOverfeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sleep Disturbances.
        /// </summary>
        internal static string EvolutionCriteriaForm_LabelSleepDisturbances {
            get {
                return ResourceManager.GetString("EvolutionCriteriaForm_LabelSleepDisturbances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Special Encounter.
        /// </summary>
        internal static string EvolutionCriteriaForm_LabelSpecialEncounter {
            get {
                return ResourceManager.GetString("EvolutionCriteriaForm_LabelSpecialEncounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stage-5.
        /// </summary>
        internal static string EvolutionCriteriaForm_LabelStage5 {
            get {
                return ResourceManager.GetString("EvolutionCriteriaForm_LabelStage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stage (Jogress).
        /// </summary>
        internal static string EvolutionCriteriaForm_LabelStageJogress {
            get {
                return ResourceManager.GetString("EvolutionCriteriaForm_LabelStageJogress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a to.
        /// </summary>
        internal static string EvolutionCriteriaForm_LabelTo {
            get {
                return ResourceManager.GetString("EvolutionCriteriaForm_LabelTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Training.
        /// </summary>
        internal static string EvolutionCriteriaForm_LabelTraining {
            get {
                return ResourceManager.GetString("EvolutionCriteriaForm_LabelTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Version (Jogress).
        /// </summary>
        internal static string EvolutionCriteriaForm_LabelVersionJogress {
            get {
                return ResourceManager.GetString("EvolutionCriteriaForm_LabelVersionJogress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Win Ratio.
        /// </summary>
        internal static string EvolutionCriteriaForm_LabelWinRatio {
            get {
                return ResourceManager.GetString("EvolutionCriteriaForm_LabelWinRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edit Evolution Criteria.
        /// </summary>
        internal static string EvolutionCriteriaForm_Title {
            get {
                return ResourceManager.GetString("EvolutionCriteriaForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Evolutions Editor.
        /// </summary>
        internal static string EvolutionsEditor_Title {
            get {
                return ResourceManager.GetString("EvolutionsEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Import sprites from &quot;{0}&quot; for this pet?
        ///The contents will be extracted to the pet&apos;s folder..
        /// </summary>
        internal static string ImportSpritesConfirm {
            get {
                return ResourceManager.GetString("ImportSpritesConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error importing sprites: {0}.
        /// </summary>
        internal static string ImportSpritesError {
            get {
                return ResourceManager.GetString("ImportSpritesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a File not found: {0}.
        /// </summary>
        internal static string ImportSpritesFileNotFound {
            get {
                return ResourceManager.GetString("ImportSpritesFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select a valid pet to import sprites..
        /// </summary>
        internal static string ImportSpritesSelectPet {
            get {
                return ResourceManager.GetString("ImportSpritesSelectPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sprites imported successfully!.
        /// </summary>
        internal static string ImportSpritesSuccess {
            get {
                return ResourceManager.GetString("ImportSpritesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Import sprites.
        /// </summary>
        internal static string ImportSpritesTitle {
            get {
                return ResourceManager.GetString("ImportSpritesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Version.
        /// </summary>
        internal static string Label_Version {
            get {
                return ResourceManager.GetString("Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ver. {0} | Stage {1}.
        /// </summary>
        internal static string Label_VersionStage {
            get {
                return ResourceManager.GetString("Label_VersionStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Version {0}.
        /// </summary>
        internal static string Label_VersionWithNumber {
            get {
                return ResourceManager.GetString("Label_VersionWithNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Module already exists..
        /// </summary>
        internal static string ModuleAlreadyExists {
            get {
                return ResourceManager.GetString("ModuleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Module folder name:.
        /// </summary>
        internal static string ModuleFolderNamePrompt {
            get {
                return ResourceManager.GetString("ModuleFolderNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Module saved!.
        /// </summary>
        internal static string ModuleSaved {
            get {
                return ResourceManager.GetString("ModuleSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Backgrounds.
        /// </summary>
        internal static string ModuleTab_TabBackgrounds {
            get {
                return ResourceManager.GetString("ModuleTab_TabBackgrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Main.
        /// </summary>
        internal static string ModuleTab_TabMain {
            get {
                return ResourceManager.GetString("ModuleTab_TabMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unlocks.
        /// </summary>
        internal static string ModuleTab_TabUnlocks {
            get {
                return ResourceManager.GetString("ModuleTab_TabUnlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  Copy.
        /// </summary>
        internal static string PetTab_CopySuffix {
            get {
                return ResourceManager.GetString("PetTab_CopySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a New Pet.
        /// </summary>
        internal static string PetTab_NewPetName {
            get {
                return ResourceManager.GetString("PetTab_NewPetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Choose the stage for the new Pet:.
        /// </summary>
        internal static string StageSelectForm_Label {
            get {
                return ResourceManager.GetString("StageSelectForm_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stage {0}.
        /// </summary>
        internal static string StageSelectForm_StageItem {
            get {
                return ResourceManager.GetString("StageSelectForm_StageItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select Stage.
        /// </summary>
        internal static string StageSelectForm_Title {
            get {
                return ResourceManager.GetString("StageSelectForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Battle.
        /// </summary>
        internal static string TabBattle {
            get {
                return ResourceManager.GetString("TabBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Item.
        /// </summary>
        internal static string TabItem {
            get {
                return ResourceManager.GetString("TabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Module.
        /// </summary>
        internal static string TabModule {
            get {
                return ResourceManager.GetString("TabModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pet.
        /// </summary>
        internal static string TabPet {
            get {
                return ResourceManager.GetString("TabPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
