using System.Collections.Generic;

namespace OmnipetModuleEditor.Models
{
    public static class PetTemplates
    {
        public static readonly Pet[] ByStage = new Pet[]
        {
            // Stage 0
            new Pet
            {
                Name = "New Pet",
                Stage = 0,
                Version = 1,
                Special = false,
                SpecialKey = null,
                Sleeps = null,
                Wakes = null,
                AtkMain = 0,
                AtkAlt = 0,
                AtkAlt2 = 0,
                Time = 1,
                PoopTimer = 0,
                Energy = 0,
                MinWeight = 0,
                EvolWeight = 0,
                Stomach = 0,
                HungerLoss = 0,
                StrengthLoss = 0,
                HealDoses = 0,
                Power = 0,
                Attribute = "",
                ConditionHearts = 0,
                JogressAvaliable = false,
                Hp = 0,
                Evolve = new List<Evolution>()
            },
            // Stage 1
            new Pet
            {
                Name = "New Pet",
                Stage = 1,
                Version = 1,
                Special = false,
                SpecialKey = null,
                Sleeps = null,
                Wakes = null,
                AtkMain = 0,
                AtkAlt = 0,
                AtkAlt2 = 0,
                Time = 10,
                PoopTimer = 3,
                Energy = 0,
                MinWeight = 5,
                EvolWeight = 0,
                Stomach = 4,
                HungerLoss = 3,
                StrengthLoss = 3,
                HealDoses = 1,
                Power = 0,
                Attribute = "",
                ConditionHearts = 1,
                JogressAvaliable = false,
                Hp = 0,
                Evolve = new List<Evolution>()
            },
            // Stage 2
            new Pet
            {
                Name = "New Pet",
                Stage = 2,
                Version = 1,
                Special = false,
                SpecialKey = null,
                Sleeps = "20:00",
                Wakes = "08:00",
                AtkMain = 0,
                AtkAlt = 0,
                AtkAlt2 = 0,
                Time = 720,
                PoopTimer = 60,
                Energy = 0,
                MinWeight = 10,
                EvolWeight = 0,
                Stomach = 4,
                HungerLoss = 30,
                StrengthLoss = 30,
                HealDoses = 1,
                Power = 0,
                Attribute = "",
                ConditionHearts = 2,
                JogressAvaliable = false,
                Hp = 0,
                Evolve = new List<Evolution>()
            },
            // Stage 3
            new Pet
            {
                Name = "New Pet",
                Stage = 3,
                Version = 1,
                Special = false,
                SpecialKey = null,
                Sleeps = "20:00",
                Wakes = "08:00",
                AtkMain = 1,
                AtkAlt = 0,
                AtkAlt2 = 0,
                Time = 1440,
                PoopTimer = 120,
                Energy = 20,
                MinWeight = 20,
                EvolWeight = 0,
                Stomach = 4,
                HungerLoss = 48,
                StrengthLoss = 48,
                HealDoses = 1,
                Power = 10,
                Attribute = "",
                ConditionHearts = 3,
                JogressAvaliable = false,
                Hp = 10,
                Evolve = new List<Evolution>()
            },
            // Stage 4
            new Pet
            {
                Name = "New Pet",
                Stage = 4,
                Version = 1,
                Special = false,
                SpecialKey = null,
                Sleeps = "21:00",
                Wakes = "08:00",
                AtkMain = 3,
                AtkAlt = 25,
                AtkAlt2 = 0,
                Time = 2160,
                PoopTimer = 120,
                Energy = 30,
                MinWeight = 30,
                EvolWeight = 0,
                Stomach = 6,
                HungerLoss = 59,
                StrengthLoss = 59,
                HealDoses = 1,
                Power = 50,
                Attribute = "",
                ConditionHearts = 4,
                JogressAvaliable = false,
                Hp = 12,
                Evolve = new List<Evolution>()
            },
            // Stage 5
            new Pet
            {
                Name = "New Pet",
                Stage = 5,
                Version = 1,
                Special = false,
                SpecialKey = null,
                Sleeps = "22:00",
                Wakes = "08:00",
                AtkMain = 10,
                AtkAlt = 2,
                AtkAlt2 = 0,
                Time = 2400,
                PoopTimer = 120,
                Energy = 40,
                MinWeight = 40,
                EvolWeight = 0,
                Stomach = 6,
                HungerLoss = 59,
                StrengthLoss = 59,
                HealDoses = 1,
                Power = 100,
                Attribute = "",
                ConditionHearts = 4,
                JogressAvaliable = true,
                Hp = 15,
                Evolve = new List<Evolution>()
            },
            // Stage 6
            new Pet
            {
                Name = "New Pet",
                Stage = 6,
                Version = 1,
                Special = false,
                SpecialKey = null,
                Sleeps = "23:00",
                Wakes = "08:00",
                AtkMain = 30,
                AtkAlt = 29,
                AtkAlt2 = 0,
                Time = 2880,
                PoopTimer = 120,
                Energy = 50,
                MinWeight = 40,
                EvolWeight = 0,
                Stomach = 8,
                HungerLoss = 59,
                StrengthLoss = 59,
                HealDoses = 1,
                Power = 150,
                Attribute = "",
                ConditionHearts = 4,
                JogressAvaliable = false,
                Hp = 18,
                Evolve = new List<Evolution>()
            },
            // Stage 7
            new Pet
            {
                Name = "New Pet",
                Stage = 7,
                Version = 1,
                Special = false,
                SpecialKey = null,
                Sleeps = "23:00",
                Wakes = "08:00",
                AtkMain = 16,
                AtkAlt = 12,
                AtkAlt2 = 0,
                Time = 2880,
                PoopTimer = 120,
                Energy = 50,
                MinWeight = 40,
                EvolWeight = 0,
                Stomach = 8,
                HungerLoss = 59,
                StrengthLoss = 59,
                HealDoses = 1,
                Power = 200,
                Attribute = "",
                ConditionHearts = 4,
                JogressAvaliable = false,
                Hp = 20,
                Evolve = new List<Evolution>()
            },
            // Stage 8 (template gen�rico, pois n�o h� exemplos nos arquivos)
            new Pet
            {
                Name = "New Pet",
                Stage = 8,
                Version = 1,
                Special = false,
                SpecialKey = null,
                Sleeps = "23:00",
                Wakes = "08:00",
                AtkMain = 16,
                AtkAlt = 12,
                AtkAlt2 = 0,
                Time = 2880,
                PoopTimer = 120,
                Energy = 50,
                MinWeight = 40,
                EvolWeight = 0,
                Stomach = 8,
                HungerLoss = 59,
                StrengthLoss = 59,
                HealDoses = 1,
                Power = 200,
                Attribute = "",
                ConditionHearts = 4,
                JogressAvaliable = false,
                Hp = 20,
                Evolve = new List<Evolution>()
            }
        };
    }
}